// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGXRiIatAksscJgTIX9zZmedhfQID7cg',
    appId: '1:19125944141:web:8eda2368c2450bbe78c104',
    messagingSenderId: '19125944141',
    projectId: 'tourism-app-170ad',
    authDomain: 'tourism-app-170ad.firebaseapp.com',
    storageBucket: 'tourism-app-170ad.firebasestorage.app',
    measurementId: 'G-PC0RYDQSRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwhTJ1xzFLZtdtmgcu0GGxjCtB9anxjs',
    appId: '1:19125944141:android:d8f6329f9825a01878c104',
    messagingSenderId: '19125944141',
    projectId: 'tourism-app-170ad',
    storageBucket: 'tourism-app-170ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmIBjzxjyr7zbzXMt23SSLaz-sibbkx6U',
    appId: '1:19125944141:ios:ee4ed5ceb096038e78c104',
    messagingSenderId: '19125944141',
    projectId: 'tourism-app-170ad',
    storageBucket: 'tourism-app-170ad.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmIBjzxjyr7zbzXMt23SSLaz-sibbkx6U',
    appId: '1:19125944141:ios:ee4ed5ceb096038e78c104',
    messagingSenderId: '19125944141',
    projectId: 'tourism-app-170ad',
    storageBucket: 'tourism-app-170ad.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrGXRiIatAksscJgTIX9zZmedhfQID7cg',
    appId: '1:19125944141:web:d152f15784f1d8fe78c104',
    messagingSenderId: '19125944141',
    projectId: 'tourism-app-170ad',
    authDomain: 'tourism-app-170ad.firebaseapp.com',
    storageBucket: 'tourism-app-170ad.firebasestorage.app',
    measurementId: 'G-VEC3S1BL50',
  );

}